name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies for client
        run: npm install
        working-directory: client
      - name: Install dependencies for server
        run: npm install
        working-directory: server
      - name: Run lint for client
        run: npm run eslint
        working-directory: client
      - name: Run lint for server
        run: npm run eslint
        working-directory: server
      - name: Build
        run: npm run build
        working-directory: client
      - name: Run tests for server
        run: npm run test
        working-directory: server
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run start:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
          working-directory: server