name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies for client
        run: npm install
        working-directory: client
      - name: Install dependencies for server
        run: npm install
        working-directory: server
      - name: Run lint for client
        run: npm run eslint
        working-directory: client
      - name: Run lint for server
        run: npm run eslint
        working-directory: server
      - name: Build
        run: npm run build
        working-directory: client
      - name: Test client
        run: npm run test
        working-directory: client
      - name: Test server
        run: npm run test
        working-directory: server
